### ISSUE TITLE
File  & folder names become invisible sometimes

### ISSUE THREAD

**Issue by adarshurs** [DevShayan/android-studio-color-theme#1]
![Screenshot 2023-04-11 at 10 03 09 AM](https://user-images.githubusercontent.com/5429221/231057098-1268384f-381b-449f-885d-455a3886bc7f.png)
![Screenshot 2023-04-11 at 10 03 19 AM](https://user-images.githubusercontent.com/5429221/231057104-485e1e08-2ac3-48ee-8c53-4673e5920bed.png)

As you can see in the screenshots, in the project explorer pan and file tabs, file & folder names become invisible(or not clearly visible) sometimes, I don't know how or when it happens. This is the second time happening. I have attached the screenshot, I hope you'll fix it in the next update.

BTW, Thanks for the theme, it's excellent :)

**Comment by Minghimea** [comment]
Reason: The color of Git Commit set by the theme is too close to the background color, which makes it difficult to distinguish 
Solution:
You can set the color to your favorite color by adding or modifying in your settings.json (search settings.json with Ctrl + Shift + P). 
```
    "workbench.colorCustomizations": {
        "[Darcula (Android Studio)]": {
		    "gitDecoration.modifiedResourceForeground": "#3E86A0",
        },
        "[Intellij light (Android Studio)]": {
		    "gitDecoration.modifiedResourceForeground": "#3E86A0",
        }
    },
```
Here I used the Git Commit color in Android Studio (approximately). 
Mmm, this plugin is really great!

**Comment by DevShayan** [comment]
The issue is fixed
